// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/health": {
            "get": {
                "description": "This gets the Gecko API health status",
                "produces": [
                    "application/json"
                ],
                "summary": "Get Gecko API health status Endpoint",
                "operationId": "checkHealth",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/price_api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/price": {
            "get": {
                "description": "Fetches the price of a given coin ticker.",
                "produces": [
                    "application/json"
                ],
                "summary": "Fetch coin price Endpoint",
                "operationId": "fetchPrice",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Coin ticker symbol",
                        "name": "ticker",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/price_api.PriceResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "price_api.HealthResponse": {
            "type": "object",
            "properties": {
                "geckoapistatus": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "price_api.PriceResponse": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "vol24Hr": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
