definitions:
  price_api.HealthResponse:
    properties:
      geckoapistatus:
        type: string
      status:
        type: string
      timestamp:
        type: string
    type: object
  price_api.PriceResponse:
    properties:
      price:
        type: number
      ticker:
        type: string
      timestamp:
        type: string
      vol24Hr:
        type: number
    type: object
info:
  contact: {}
paths:
  /v1/health:
    get:
      description: This gets the Gecko API health status
      operationId: checkHealth
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/price_api.HealthResponse'
      summary: Get Gecko API health status Endpoint
  /v1/price:
    get:
      description: Fetches the price of a given coin ticker.
      operationId: fetchPrice
      parameters:
      - description: Coin ticker symbol
        in: query
        name: ticker
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/price_api.PriceResponse'
      summary: Fetch coin price Endpoint
swagger: "2.0"
